spring.application.name: banana-client4-sentinel
spring:
  cloud:
    openfeign:
      httpclient:
        enabled: false
      okhttp:
        enabled: true
    sentinel:
      transport:
        port: 10201
        dashboard: localhost:10300
    zookeeper:
      connect-string: localhost:2181
server:
  port: 10200
  servlet:
    context-path: /client4
## feign支持sentinel
feign:
  sentinel:
    enabled: true
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: io.rainforest.banana.client.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    # Basic认证用户名
    username: yulin
    # Basic认证密码
    password: 123yl.